name: exp5_b
description: A Flutter app showing state management using Provider
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  b: ^0.2.0
  flutter:
    sdk: flutter
  provider: ^6.1.2   # ✅ add provider

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
